services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatbot-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    networks:
      - chatbot-network
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - chatbot-network
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - chatbot-network
    restart: unless-stopped


  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC receiver
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yaml
    networks:
      - chatbot-network
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # gRPC receiver
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

    networks:
      - chatbot-network
    restart: unless-stopped

volumes:
  mongodb_data:
  zookeeper_data:
  kafka_data:

networks:
  chatbot-network:
    name: chatbot-network
